### PR TITLE
add conan to path after installation

### PR DESCRIPTION
**Pull request by aminya**

### CODE REVIEW

**Comment by aminya** [comment]
@Xav83 Could you merge this?

**Review by Xav83 — APPROVED** [review]
LGTM ✔️

**Comment by Xav83** [comment]
Thank you @aminya for your contribution 🙂

**Comment by Xav83** [comment]
FYI, a [new version of conan (1.33.0)](https://chocolatey.org/packages/conan) is available and should integrate the modification from this Pull Request. 😉

**Pull request merged**
