### PR TITLE
achievement-watcher: make package locally-installable and disable built-in auto-update

### PR DESCRIPTION
**Pull request by soredake**
@Xav83

### CODE REVIEW

**Review by Xav83 — APPROVED** [review]

**Comment by Xav83** [comment]
Thank you @soredake for this changes.
It will definitely make the user experience with this package much more enjoyable :slightly_smiling_face:

**Comment by soredake** [comment]
@Xav83 will you publish updated package to chocolatey repo later?

**Comment by Xav83** [comment]
@soredake Can't we wait for the next update of the software `achievement-watcher` ? Then, the new version of the package will automatically embed the modification of this Pull Request, and the issue will be solved automatically.

If I understand correctly, the issue comes when a new update of the the software is available.
Or maybe, you want to install a specific older version ? :upside_down_face:

**Comment by soredake** [comment]
@Xav83 the main reason why i created this pr is to disable auto-update cause this software is dead, there will be probably no releases for a long time, if ever, waiting for a new release is pointless.

image
image

**Comment by soredake** [comment]
@Xav83 sorry to bother you but can you please release a new version of 
achievement-watcher package to chocolatey repo so my changes will be actually used?

**Pull request merged**
